alias update='sudo aptitude update && sudo aptitude upgrade'
alias sinc='rsync -av /home/eduardo/USP/ /media/eduardo/Eduardo/USP'
alias sincdel='rsync -av --delete /home/eduardo/USP/ /media/eduardo/Eduardo/USP'
alias tohd='rsync -av --delete /home/eduardo/USP/ /media/Heisenberg/USP'
alias tofep='rsync --delete -av -e ssh /home/eduardo/USP/ eduardos@fep.if.usp.br:PC_USP/'
alias fromfep='rsync --delete -av -e ssh eduardos@fep.if.usp.br:PC_USP/ /home/eduardo/USP/'
alias cls='clear'
alias fep='ssh eduardos@fep.if.usp.br'
alias graaf='ssh graaf.intra.if.usp.br'
alias roadking='ssh 10.6.0.206'
alias e='emacs -nw'
alias osmc='ssh osmc@192.168.0.100'
alias tomecao='rsync -av --delete -e ssh /home/eduardo/USP/ eduardo@192.168.0.105:~/USP/'

