[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']

[custom-keybindings/custom0]
binding='<Control><Alt>t'
command='kgx'
name='Console'

[custom-keybindings/custom1]
binding='<Super>f'
command='nautilus'
name='Files'

[custom-keybindings/custom2]
binding='<Super>w'
command='firefox-esr'
name='Firefox'
